const strategies = [
  {
    id: 0,
    name: "USDC 10x Yearn",
    desc: "Gearbox Levered",
    longDesc: "Deposit USDC, and earn yield on yearn with 10x leverage.",
    asset: "USDC",
    leverage: 10,
    apy: 52,
    tvl: 230,
    imgSrc: "https://www.cryptofonts.com/img/icons/usdc.svg",
  },
  {
    id: 1,
    name: "ETH 5x Lido",
    desc: "Gearbox Levered",
    longDesc: "Deposit USDC, and earn yield on yearn with 10x leverage.",
    asset: "ETH",
    leverage: 10,
    apy: 22,
    tvl: 500,
    imgSrc: "https://www.cryptofonts.com/img/icons/eth.svg",
  },
  {
    id: 2,
    name: "Exotic Options",
    desc: "Gearbox Levered",
    longDesc: "Deposit USDC, and earn yield on yearn with 10x leverage.",
    asset: "UniLP",
    leverage: 10,
    apy: 60,
    tvl: 730,
    imgSrc: "https://www.cryptofonts.com/img/icons/options.svg",
  },
  {
    id: 3,
    name: "USDT 10x Curve",
    desc: "Gearbox Levered",
    longDesc: "Deposit USDC, and earn yield on yearn with 10x leverage.",
    asset: "USDT",
    leverage: 10,
    apy: 62,
    tvl: 310,
    imgSrc: "https://www.cryptofonts.com/img/icons/usdt.svg",
  },
  {
    id: 4,
    name: "WBTC 5x Curve",
    desc: "Gearbox Levered",
    longDesc: "Deposit USDC, and earn yield on yearn with 10x leverage.",
    asset: "WBTC",
    leverage: 10,
    apy: 12,
    tvl: 100,
    imgSrc: "https://www.cryptofonts.com/img/icons/wbtc.svg",
  },
  {
    id: 5,
    name: "DAI 10x Yearn",
    desc: "Gearbox Leveraged",
    longDesc: "Deposit USDC, and earn yield on yearn with 10x leverage.",
    asset: "DAI",
    leverage: 10,
    apy: 23,
    tvl: 120,
    imgSrc: "https://www.cryptofonts.com/img/icons/dai.svg",
  },
];

export default strategies;
